repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--strict, --config-file=pyproject.toml]
        additional_dependencies:
          - pandas-stubs         # pandas typing
          - pydantic>=2          # so BaseModel resolves & plugin activates
          - pytest               # so pytest imports resolve
          - hypothesis           # tests use hypothesis
          - freezegun            # tests import freezegun
