from typing import Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

class Typer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def callback(self, *args: Any, **kwargs: Any) -> Callable[[F], F]: ...
    def command(self, *args: Any, **kwargs: Any) -> Callable[[F], F]: ...

def Option(*args: Any, **kwargs: Any) -> Any: ...
